Added Color Swatch Column
RVxLab/filament-colorpicker pull request #8
Opened 2022-01-26 22:04 UTC by morganchorlton3

Added simple color swatch column for filament table

2022-01-26 22:07 UTC, RVxLab commented
Related discussion: https://github.com/RVxLab/filament-colorpicker/discussions/7

2022-01-26 22:10 UTC, RVxLab commented
Looks good code wise, I'll check it out visually later today. Thanks for the PR!

2022-01-26 22:12 UTC, morganchorlton3 commented
Brill Thanks a lot, and thanks for the help with my first contribution to an open source project :)

2022-01-27 06:01 UTC, RVxLab requested changes
There are a couple of changes that are needed. In the current state the swatch causes a view not found error.

2022-01-27 06:01 UTC, RVxLab commented on resources/views/colorswatch.blade.php
> +<div style="background-color: {{ $getState() }}; width: 3rem; height: 1.75rem; margin-left: 1rem; border-radius: 10px;">
```suggestion
<div style="background-color: {{ $getState() }}; width: 1.5rem; height: 1.5rem; margin-left: 1rem; border-radius: 6px;">
```

2022-01-27 23:31 UTC, RVxLab approved these changes

2022-01-28 08:01 UTC, merged